# Generated by Django 4.2.30 on 2026-05-13 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Set to False when an element is deleted",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("government", "Government"),
                            ("university", "University"),
                            ("ngo", "NGO / Non-profit"),
                            ("research", "Research Institute"),
                            ("startup", "Startup"),
                            ("cooperative", "Cooperative"),
                            ("other", "Other"),
                        ],
                        default="company",
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Automotive", "Automotive"),
                            ("Technology", "Technology"),
                            ("Energy", "Energy"),
                            ("Chemical", "Chemical"),
                            ("Food", "Food"),
                            ("Pharmaceutical", "Pharmaceutical"),
                            ("Textile and Fashion", "Textile and Fashion"),
                            ("Construction", "Construction"),
                            ("Financial Services", "Financial Services"),
                            ("Tourism and Hospitality", "Tourism and Hospitality"),
                            ("Entertainment", "Entertainment"),
                            ("Mining", "Mining"),
                            (
                                "Transportation and Logistics",
                                "Transportation and Logistics",
                            ),
                            ("Shipbuilding", "Shipbuilding"),
                            ("Agriculture and Livestock", "Agriculture and Livestock"),
                            (
                                "Healthcare and Biotechnology",
                                "Healthcare and Biotechnology",
                            ),
                            ("Defense and Security", "Defense and Security"),
                            ("Professional Services", "Professional Services"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Argentina", "Argentina"),
                            ("Bahamas", "Bahamas"),
                            ("Barbados", "Barbados"),
                            ("Belize", "Belize"),
                            ("Bolivia", "Bolivia"),
                            ("Brazil", "Brazil"),
                            ("Chile", "Chile"),
                            ("Colombia", "Colombia"),
                            ("Costa Rica", "Costa Rica"),
                            ("Cuba", "Cuba"),
                            ("Dominica", "Dominica"),
                            ("Ecuador", "Ecuador"),
                            ("El Salvador", "El Salvador"),
                            ("Grenada", "Grenada"),
                            ("Guatemala", "Guatemala"),
                            ("Guyana", "Guyana"),
                            ("Haiti", "Haiti"),
                            ("Honduras", "Honduras"),
                            ("Jamaica", "Jamaica"),
                            ("Mexico", "Mexico"),
                            ("Nicaragua", "Nicaragua"),
                            ("Panama", "Panama"),
                            ("Paraguay", "Paraguay"),
                            ("Peru", "Peru"),
                            ("Puerto Rico", "Puerto Rico"),
                            ("Dominican Republic", "Dominican Republic"),
                            ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
                            ("Saint Lucia", "Saint Lucia"),
                            (
                                "Saint Vincent and the Grenadines",
                                "Saint Vincent and the Grenadines",
                            ),
                            ("Suriname", "Suriname"),
                            ("Trinidad and Tobago", "Trinidad and Tobago"),
                            ("Uruguay", "Uruguay"),
                            ("Venezuela", "Venezuela"),
                            ("United States of America", "United States of America"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("logo_url", models.URLField(blank=True, default="")),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Set to False when an element is deleted",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private - invitation only"),
                            ("internal", "Internal - visible to org members"),
                            ("public", "Public - visible to all Glapagos users"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("lgpd", "Brazil - LGPD"),
                            (
                                "mexico_pdpa",
                                "Mexico - Ley Federal de Proteccion de Datos",
                            ),
                            ("colombia", "Colombia - Ley 1581"),
                            ("argentina", "Argentina - PDPA"),
                            ("gdpr", "EU - GDPR"),
                            ("ccpa", "USA - CCPA"),
                            ("none", "No specific jurisdiction"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("ai_model", models.CharField(blank=True, default="", max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="workspaces.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "ordering": ["organization", "name"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Set to False when an element is deleted",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("contributor", "Contributor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("invitation_accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Membership",
                "verbose_name_plural": "Workspace Memberships",
                "ordering": ["workspace", "role"],
                "unique_together": {("workspace", "user")},
            },
        ),
    ]
